name: binding-rust-static-lib

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".github/workflows/standalone.yml"
      - ".github/workflows/ci-build.yml"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/workflows/standalone.yml"
      - ".github/workflows/ci-build.yml"

jobs:
  build_ubuntu:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rust: [stable]
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - name: Checkout WasmEdge Rust SDK
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt update
          apt install -y software-properties-common llvm-15-dev liblld-15-dev ninja-build

      - name: Install build dependencies
        run: |
          apt install -y libzstd-dev libfmt-dev

      - name: Install Rust-stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Test Rust SDK
        run: |
          cargo test --workspace --exclude async-wasi --features bundled,aot,ffi -- --nocapture --test-threads=1 --skip test_vmbuilder

      - name: Test Rust SDK with async feature
        run: |
          cargo test --workspace --features bundled,aot,async,ffi -- --nocapture --test-threads=1 --skip test_vmbuilder
